### ISSUE TITLE
Allow collaborators to use resin-sync

### ISSUE THREAD

**Issue by dakrawczyk** [resin-io-modules/resin-sync#36]
Hey there. I have been shared the "Glance" app by user: gh_iitgrad. When I attempt 'resin sync Glance' it fails because "user gh_dakrawczyk does not have permission to access device 2257....."

After talking to support, it was discovered that this is intentional behavior. As a user who works on a team, it is not effective for me to need to push every time I make a small change. 

Can this enhancement be investigated? Thanks!

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_l38)

**Comment by lekkas** [comment]
Hey @dakrawczyk ,

Thank you for your comment, we really appreciate your feedback and feature requests.

Indeed, this is intentional behavior, and the reason for limiting `resin sync` to device owners only is to keep it simple, at least for now. Allowing multiple users to perform 'resin sync' on the same device is will require some non trivial changes on our backend to manage concurrent `resin sync` synchronization as well as proper notification of users attempting them.

That said, we haven't turned this feature down and its priority will probably be reassessed soon, but I'm afraid I can't give you any concrete time estimations.

One way to work around this is to provision your own device in the 'Glance' application. A device owner essentially is the user that has provisioned it, so resin sync will work in that case.

**Comment by dakrawczyk** [comment]
@lekkas Thank you for the response. 

Since I work right next to the only other person that has access to the device, we are not worried about two `resin sync`'s going on at the same time. My coworker has provisioned the device we share to his account. Is there any way I could use his account to perform `resin sync`?

**Comment by lekkas** [comment]
Hey @dakrawczyk, sorry for the delayed reply on this.

One way to work around the current limitation would be to provision a new device into a new application from your account and then move the device into the application that you collaborate on. But unfortunately that will not be feasible if there's only a single device that you share.

In general, we do not encourage account sharing between users, but yes, the account credentials (user/pass or Auth Token) of the device owner can be used to login with the CLI using `resin login`. The workstation from which `resin sync` is going to be performed must also have access to an SSH key - for more information on how to add this you can revisit our guide [here](http://docs.resin.io/raspberrypi2/nodejs/getting-started/#adding-an-ssh-key).

Sorry for any inconvenience this may have caused to you.

**Comment by imrehg** [comment]
This would indeed be a very useful feature (experienced during our demos at ELCE as well).
